// Static one-time seed profiles from the uploaded account list.
// These are explicit seed values, not runtime-generated avatars.

const SEEDED_PROFILES = [
  { name: 'Marcus Vance', username: 'marcus_v', description: 'Cloud architect.', image: 'https://randomuser.me/api/portraits/men/11.jpg' },
  { name: 'chloe', username: 'chloebirdie', description: 'Just cat pics. 🐈', image: 'https://randomuser.me/api/portraits/women/11.jpg' },
  { name: 'Linda Miller', username: 'lindamiller1962', description: 'Proud grandma. 👵', image: 'https://randomuser.me/api/portraits/women/62.jpg' },
  { name: 'Jaxon', username: 'xx_jaxon_xx', description: 'Twitch streamer. 🎮', image: 'https://randomuser.me/api/portraits/men/12.jpg' },
  { name: 'Sarah T.', username: 'sarah_explores', description: 'NYC to Tokyo. 🗽🗾', image: 'https://randomuser.me/api/portraits/women/12.jpg' },
  { name: 'dave', username: 'dave', description: 'just here.', image: 'https://randomuser.me/api/portraits/men/13.jpg' },
  { name: 'Dr. Alan Grant', username: 'agrant_phd', description: 'Paleontology research.', image: 'https://randomuser.me/api/portraits/men/63.jpg' },
  { name: 'Mia', username: 'mia_wants_sleep', description: 'Tired nursing student. 🩺', image: 'https://randomuser.me/api/portraits/women/13.jpg' },
  { name: 'BRYAN', username: 'BRYANGYMBRO', description: 'GYM 24/7. 💪', image: 'https://randomuser.me/api/portraits/men/14.jpg' },
  { name: 'ellie', username: 'ellie_reads', description: 'Dark academia aesthetic. 🕯️📚', image: 'https://randomuser.me/api/portraits/women/14.jpg' },
  { name: 'Tyler Smith', username: 'tsmith_invest', description: 'Value investing & Crypto. 📈', image: 'https://randomuser.me/api/portraits/men/15.jpg' },
  { name: 'a.', username: 'alice_in_w', description: 'Soft vibes only. 🌸', image: 'https://randomuser.me/api/portraits/women/15.jpg' },
  { name: 'Robert Jenkins', username: 'robert_j_55', description: 'Go Packers!', image: 'https://randomuser.me/api/portraits/men/64.jpg' },
  { name: 'vamp kid', username: 'vamp_kid', description: 'Ur local menace.', image: 'https://randomuser.me/api/portraits/men/16.jpg' },
  { name: 'Chef Mateo', username: 'mateocooks', description: 'Head Chef. 🍳', image: 'https://randomuser.me/api/portraits/men/17.jpg' },
  { name: 'samantha', username: 'sammy_sunshine', description: 'Living & laughing. ☀️', image: 'https://randomuser.me/api/portraits/women/16.jpg' },
  { name: 'User489102', username: 'user489102', description: 'Default bio.', image: 'https://randomuser.me/api/portraits/men/18.jpg' },
  { name: 'Priya Patel', username: 'priyadesigns', description: 'UX/UI Designer. 🎨', image: 'https://randomuser.me/api/portraits/women/17.jpg' },
  { name: 'jay', username: 'jay_no_cap', description: 'Everything is expensive. 💸', image: 'https://randomuser.me/api/portraits/men/19.jpg' },
  { name: 'Evelyn Rose', username: 'evelyn_gardens', description: 'Plant mom. 🌱', image: 'https://randomuser.me/api/portraits/women/18.jpg' },
  { name: 'The Daily Tech', username: 'dailytechnews', description: 'Tech & AI news. 🤖', image: 'https://randomuser.me/api/portraits/men/20.jpg' },
  { name: 'mike', username: 'mike_drops', description: 'Aspiring comic.', image: 'https://randomuser.me/api/portraits/men/21.jpg' },
  { name: 'Sophia', username: 'sophia_study', description: 'Med school journey. 🩺', image: 'https://randomuser.me/api/portraits/women/19.jpg' },
  { name: 'BIG TONE', username: 'tony_pizza', description: 'Best Jersey pizza. 🍕', image: 'https://randomuser.me/api/portraits/men/22.jpg' },
  { name: 'natalie', username: 'nat_nat_nat', description: 'Corporate fairy. 🧚‍♀️✨', image: 'https://randomuser.me/api/portraits/women/20.jpg' },
  { name: 'Kevin H.', username: 'kevinh_writer', description: 'Freelance journalist.', image: 'https://randomuser.me/api/portraits/men/23.jpg' },
  { name: 'zack', username: 'zack_attack', description: 'Retweeting memes.', image: 'https://randomuser.me/api/portraits/men/24.jpg' },
  { name: 'Amanda', username: 'amanda_runs', description: 'Marathon finisher! 🏃‍♀️🏅', image: 'https://randomuser.me/api/portraits/women/21.jpg' },
  { name: '□□□□□□', username: 'void_gazer', description: 'Nothing matters.', image: 'https://randomuser.me/api/portraits/men/25.jpg' },
  { name: 'Emily', username: 'em_bakes_cakes', description: 'Baking messes. 🧁', image: 'https://randomuser.me/api/portraits/women/22.jpg' },
  { name: 'Greg', username: 'greg_t_garage', description: "'69 Camaro build. 🛠️", image: 'https://randomuser.me/api/portraits/men/26.jpg' },
  { name: 'lola', username: 'lolalolalola', description: 'Shopping addict. 🛍️', image: 'https://randomuser.me/api/portraits/women/23.jpg' },
  { name: 'Prof. Wright', username: 'profwright_history', description: 'History Professor.', image: 'https://randomuser.me/api/portraits/men/65.jpg' },
  { name: 'ash', username: 'ash_ketchum_ir', description: 'The very best.', image: 'https://randomuser.me/api/portraits/men/27.jpg' },
  { name: 'Brenda', username: 'brendas_boutique', description: 'Handmade soaps. 🧼', image: 'https://randomuser.me/api/portraits/women/64.jpg' },
  { name: 'noah', username: 'noah_vfx', description: '3D motion graphics.', image: 'https://randomuser.me/api/portraits/men/28.jpg' },
  { name: 'Lily', username: 'lily_cosplay', description: 'Prop maker & cosplayer.', image: 'https://randomuser.me/api/portraits/women/24.jpg' },
  { name: 'Frank', username: 'frankie_fishing', description: 'Gone fishing. 🎣', image: 'https://randomuser.me/api/portraits/men/66.jpg' },
  { name: 'Tasha', username: 'tasha_manifests', description: 'Tarot & manifesting. 🔮', image: 'https://randomuser.me/api/portraits/women/25.jpg' },
  { name: 'chris', username: 'chris_chilling', description: 'Just vibing.', image: 'https://randomuser.me/api/portraits/men/29.jpg' },
  { name: 'Dr. Patel', username: 'dr_patel_vet', description: 'Veterinarian. 🐾', image: 'https://randomuser.me/api/portraits/men/67.jpg' },
  { name: 'xoxo', username: 'gossip_grl', description: 'You know you love me.', image: 'https://randomuser.me/api/portraits/women/26.jpg' },
  { name: 'William', username: 'william_creates', description: 'Custom woodworking. 🪵', image: 'https://randomuser.me/api/portraits/men/30.jpg' },
  { name: 'jess', username: 'jess_in_japan', description: 'Expat in Tokyo. 🗾', image: 'https://randomuser.me/api/portraits/women/27.jpg' },
  { name: 'Mark', username: 'mark_marketing', description: 'SaaS Growth Marketer.', image: 'https://randomuser.me/api/portraits/men/31.jpg' },
  { name: 'ray', username: 'ray_of_sunshine', description: 'Optimistic nihilist. ☀️', image: 'https://randomuser.me/api/portraits/men/32.jpg' },
  { name: 'Susan', username: 'susan_wine_time', description: 'Wine time! 🍷', image: 'https://randomuser.me/api/portraits/women/65.jpg' },
  { name: 'Alex', username: 'alex_the_archer', description: 'Traditional archery. 🏹', image: 'https://randomuser.me/api/portraits/men/33.jpg' },
  { name: 'b', username: 'b_random', description: 'Pressing buttons.', image: 'https://randomuser.me/api/portraits/men/34.jpg' },
  { name: 'Victor', username: 'victor_music', description: 'Indie artist. 🎙️', image: 'https://randomuser.me/api/portraits/men/35.jpg' },
];

const SEEDED_PROFILE_IMAGES = Object.fromEntries(SEEDED_PROFILES.map((profile) => [profile.username, profile.image]));
const SEEDED_PROFILE_BY_USERNAME = Object.fromEntries(SEEDED_PROFILES.map((profile) => [profile.username, profile]));
const GUEST_PROFILE_IMAGE = '/uploads/profileDefault.svg';

module.exports = { SEEDED_PROFILES, SEEDED_PROFILE_IMAGES, SEEDED_PROFILE_BY_USERNAME, GUEST_PROFILE_IMAGE };
